apiVersion: v1
kind: Service
metadata:
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: ui-api
  name: system
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: ui-api
  selector:
    deployment: system-app
