apiVersion: v1
kind: Secret
metadata:
  labels:
    app: $(APP_LABEL)
    threescale_component: system
  name: system-events-hook
stringData:
  PASSWORD: $(SYSTEM_BACKEND_SHARED_SECRET)
  URL: http://system-master:3000/master/events/import
type: Opaque